version: "3.1"
services:
  API:
    image: "emersson/servicecurso:v1"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/ms-course
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ms-course
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
# docker build -t ms-curso .
# docker swarm init
# docker node ls
# docker service create --name <service name> <image name>
# docker service ls
# docker stack deploy -c docker-compose.yml nomedoservico
# docker service update --publish-add 8080:8080 servicecurso
# docker service update --replicas 5 servicecurso_API

# docker service rm <SERVICE>
# docker kill <SERVICE>

